import numpy as np
from PIL import Image
import cv2
import time

# SIZE = 10 --> SIZE OF GAME SPACE?
HM_EPISODES = 25000
MOVE_PENALTY = 1
ENEMY_ATTACK_PENALTY = 10
ENEMY_KILL_PENALTY = 500
# BELOW IS SYNONYMOUS WITH FOOD REWARD
ATTACK_REWARD = 25
ATTACK_FINAL_REWARD = 100
TOWER_ATTACK_REWARD = 200

epsilon = 0.9
EPS_DECAY = 0.9998

# HOW MANY TIMES WE WANT TO SHOW Q-LEARNING OUTPUT
SHOW_EVERY = 3000

start_q_table = None # or filename

LEARNING_RATE = 0.1
DISCOUT = 0.95

# KEYS
PLAYER_N = 1
FOOD_N = 2

